on:
  push:
    tags:
      - '*'
  workflow_call:
    inputs:
      tag:
        type: string
permissions:
  contents: write
name: Release
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    container: ghcr.io/sergeymakinen/ci:debian
    steps:
      - name: Release
        uses: sergeymakinen/ci/release@main
        with:
          tag: ${{ inputs.tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
